export interface TransportAccountingSR {
    additionalExpenses: string | '';
    addressOfDelivery: string | '';
    cargo: string | '';
    client: string | '';
    clientLead: string | '';
    contractor: string | '';
    contractorRate: string | '';
    dateOfBill: string | '';
    dateOfPaymentContractor: string | '';
    dateOfPickup: string | '';
    dateOfSubmission: string | '';
    datePayment: string | '';
    departmentHead: string | '';
    driver: string | '';
    formPayAs: string | '';
    formPayHim: string | '';
    id: number;
    listName: string;
    income: string | '';
    incomeLearned: string | '';
    manager: string | '';
    numberOfBill: string | '';
    numberOfBillAdd: string | '';
    numberOfContainer: string | '';
    ourFirm: string | '';
    salesManager: string | '';
    sumIssued: string | '';
    summa: string | '';
    taxes: string | '';
    typeOfContainer: string | '';
}